add_rules("mode.debug", "mode.release")

set_allowedplats("windows")
set_allowedarchs("x86")

add_moduledirs("xmake/modules")
includes("xmake/modules/common_tool.lua")

includes("xmake/options.lua")
includes("xmake/3rdparty.lua")
includes("xmake/rules.lua")

target("CoreModule")
    set_kind("static")
    set_languages("cxxlatest")
    add_deps("rttr")
    add_headerfiles("src/core/**.h")
    add_headerfiles("src/core/**.hpp")
    add_files("src/core/**.cpp")
    add_includedirs("src", "src/core")
    add_filegroups("CoreModule", {rootdir = "src"})

target("YrExtensionCore")
    set_kind("shared")
    set_languages("cxxlatest")
    add_rules("codegen-cpp")
    add_deps("CoreModule", "spdlog", { public = false })
    add_deps("YRpp")
    add_headerfiles("src/yr/**.h")
    add_headerfiles("src/yr/**.hpp")
    add_files("src/yr/**.cpp")
    add_includedirs("src", "src/yr")
    add_filegroups("YrExtensionCore", {rootdir = "src"})

target("YrScripting")
    set_kind("shared")
    set_languages("cxxlatest")
    add_rules("codegen-cpp")
    add_deps("CoreModule", "YrExtensionCore", "entt", "imgui", "spdlog", { public = false })
    -- add_packages("rttr", {public = false})
    add_headerfiles("src/scripting/**.h")
    add_headerfiles("src/scripting/**.hpp")
    add_files("src/scripting/**.cpp")
    add_includedirs("src", "src/scripting", {public = false})
    add_filegroups("Engine", {rootdir = "src"})
