add_requires("boost", {configs = {context = true, coroutine = true}})
add_requires("utfcpp")
add_requires("efsw")
add_requires("spdlog")
add_requires("stb")

includes("3rdparty/YRpp.lua")
includes("3rdparty/entt.lua")
includes("3rdparty/imgui.lua")
includes("3rdparty/CppHeaderTool.lua")
includes("3rdparty/json.lua")
includes("3rdparty/v8.lua")
includes("3rdparty/puerts.lua")
