add_requires("xmake::boost", {alias = "boost", configs = {nowide = true, container = true, stacktrace = true}})
add_requires("utfcpp")
add_requires("efsw")
add_requires("spdlog")
add_requires("stb")
add_requires("cereal")
add_requires("cppzmq")
add_requires("msgpack-cxx", {configs = {boost = false}})
add_requires("asmjit")
add_requires("zydis")
add_requires("taskflow")

includes("3rdparty/YRpp.lua")
includes("3rdparty/entt.lua")
includes("3rdparty/imgui.lua")
includes("3rdparty/CppHeaderTool.lua")
includes("3rdparty/json.lua")
-- includes("3rdparty/v8.lua")
includes("3rdparty/nodejs.lua")
includes("3rdparty/puerts.lua")
includes("3rdparty/Jolt.lua")
includes("3rdparty/Wwise.lua")
includes("3rdparty/gainput.lua")
